[package]
name = "nocfree-and-rust"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[features]
default = ["layout-ansi", "backlight-perceptual"]
layout-ansi = []
layout-iso = []
layout-jis = []
layout-kr = []
backlight-perceptual = []
ble-host-wake-diagnostic = []

[dependencies]
embedded-hal-async = "1"

[target.'cfg(target_arch = "arm")'.dependencies]
nrf-softdevice = { path = "vendor/nrf-softdevice", features = [
    "ble-central",
    "ble-gatt-client",
    "ble-gatt-server",
    "ble-peripheral",
    "ble-sec",
    "critical-section-impl",
    "nrf52833",
    "s140",
] }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.9", features = [
    "arch-cortex-m",
    "executor-thread",
] }
embassy-futures = "0.1"
embassy-nrf = { version = "0.8", features = [
    "gpiote",
    "nfc-pins-as-gpio",
    "nrf52833",
    "time",
    "time-driver-rtc1",
    "unstable-pac",
] }
embassy-sync = "0.7.2"
embassy-time = { version = "0.5", features = ["tick-hz-32_768"] }
embassy-usb = "0.5.1"
embedded-storage-async = "0.4"
static_cell = "2"

[profile.dev]
codegen-units = 1
opt-level = 1
panic = "abort"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
overflow-checks = false
panic = "abort"

[[bin]]
name = "central"
path = "src/bin/central.rs"
test = false
bench = false

[[bin]]
name = "right"
path = "src/bin/right.rs"
test = false
bench = false
